### ISSUE TITLE
Name is overwritten by Id on model init

### ISSUE THREAD

**Issue by atarix83** [udos86/ng-dynamic-forms#600] opened 2017-11-23 16:29 UTC
Hi,

I would ask if there is some reason for that name is overwritten by Id value when a new instance of DynamicFormControlModel is created, or is a bug?
It would be useful sometimes to keep Id and name separated.

I paste the code line
https://github.com/udos86/ng-dynamic-forms/blob/9f8cd8320729fadbfee38adf8bad7a39952de724/packages/core/src/model/dynamic-form-control.model.ts#L64

Thanks

**Comment by udos86** [comment] 2017-11-25 20:10
@atarix83 Hi Guiseppe!

> I would ask if there is some reason for that name is overwritten by Id value when a new instance of DynamicFormControlModel is created, or is a bug?

It's not a bug, it's intentional. To a certain degree Angular forms rely on `name` attribute and I wanted to avoid any possible bugs due to naming differences between `id` and `name`.

> It would be useful sometimes to keep Id and name separated.

Could you please point that out?

**Comment by atarix83** [comment] 2017-11-27 11:57
> Could you please point that out?

I have a forms that describe a resource with some metadata. My problem is that the key of metadata, that should be the form field's id, could contains a dot (e.g. "dc.title"). I would use the name to store the real metadata key because saving the key with dot into id generates an error.
At the moment my solution is to set the model name after the model has been instantiated.

**Comment by udos86** [comment] 2017-11-27 21:55
@atarix83 

Alright, I'll take it into consideration bringing this back!

**Comment by atarix83** [comment] 2017-11-30 08:40
@udos86 thank you so much!!

**Comment by udos86** [comment] 2017-12-06 21:04
@atarix83 @PartyArk 

Alright, this will be part of `5.1.2`

**Closed** 2017-12-07 18:59 UTC
Labels: core, proposal, question

**Comment by ar27111994** [comment] 2018-01-02 12:35
Hi @udos86 @atarix83 , I'm still facing this issue, even though I am using the latest version `5.4.1` with `Ionic UI`. Please help.

![bug1](https://user-images.githubusercontent.com/13036687/34483921-467bbaee-efe3-11e7-9140-5dbcca8091b0.JPG)
![bug2](https://user-images.githubusercontent.com/13036687/34483935-5c013cea-efe3-11e7-8b67-d1571153eedf.JPG)
